export const projectData = {
    'PROJ_001': {
        id: 'PROJ_001',
        type: 'project',
        name: 'The Shining',
        code: 'SHINING-1980',
        description: 'A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0059.jpg',
        children: ['SEQ01', 'SEQ02', 'SEQ03', 'SEQ04', 'SEQ05', 'SEQ06', 'SEQ07', 'SEQ08', 'SEQ09'],
        studio: 'Warner Bros.'
    },
    'SEQ01': {
        id: 'SEQ01',
        type: 'sequence',
        name: 'Opening & Interview',
        code: 'S01',
        description: 'Sequence 1: Opening & Interview',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0023.jpg',
        children: ['SC_1', 'SC_2', 'SC_3', 'SC_4', 'SC_5'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SEQ02': {
        id: 'SEQ02',
        type: 'sequence',
        name: 'Closing Day: arrival & tour',
        code: 'S02',
        description: 'Sequence 2: Closing Day: arrival & tour',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0033.jpg',
        children: ['SC_6', 'SC_7', 'SC_8', 'SC_9', 'SC_10', 'SC_11', 'SC_12', 'SC_13'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SEQ03': {
        id: 'SEQ03',
        type: 'sequence',
        name: 'A Month Later: routine & first symptoms',
        code: 'S03',
        description: 'Sequence 3: A Month Later: routine & first symptoms',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0046.jpg',
        children: ['SC_14', 'SC_15', 'SC_16', 'SC_17', 'SC_18'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SEQ04': {
        id: 'SEQ04',
        type: 'sequence',
        name: 'TUESDAY: Room 237 beckons',
        code: 'S04',
        description: 'Sequence 4: TUESDAY: Room 237 beckons',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0058.jpg',
        children: ['SC_19', 'SC_20'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SEQ05': {
        id: 'SEQ05',
        type: 'sequence',
        name: 'THURSDAY → SATURDAY: snow & comms loss',
        code: 'S05',
        description: 'Sequence 5: THURSDAY → SATURDAY: snow & comms loss',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0084.jpg',
        children: ['SC_21', 'SC_22', 'SC_23'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SEQ06': {
        id: 'SEQ06',
        type: 'sequence',
        name: 'MONDAY: quiet unease',
        code: 'S06',
        description: 'Sequence 6: MONDAY: quiet unease',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0009.jpg',
        children: ['SC_24', 'SC_25'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SEQ07': {
        id: 'SEQ07',
        type: 'sequence',
        name: 'WEDNESDAY: the ball & 237',
        code: 'S07',
        description: 'Sequence 7: WEDNESDAY: the ball & 237',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0031.jpg',
        children: ['SC_26', 'SC_27', 'SC_28'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SEQ08': {
        id: 'SEQ08',
        type: 'sequence',
        name: 'Room 237 & denial',
        code: 'S08',
        description: 'Sequence 8: Room 237 & denial',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0053.jpg',
        children: ['SC_29', 'SC_30', 'SC_31'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SEQ09': {
        id: 'SEQ09',
        type: 'sequence',
        name: "Wendy's resolve & Jack's panic",
        code: 'S09',
        description: 'Sequence 9: Wendy\'s resolve & Jack\'s panic',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0058.jpg',
        children: ['SC_32', 'SC_33', 'SC_34', 'SC_35', 'SC_36', 'SC_37', 'SC_38'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_1': {
        id: 'SC_1',
        type: 'scene',
        name: 'EXT. MOUNTAINS – DAY',
        code: 'S01-S01',
        description: 'Aerial/drive-by: yellow VW climbs toward the Overlook.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0033.jpg',
        children: ['SHOT_1', 'SHOT_2'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_2': {
        id: 'SC_2',
        type: 'scene',
        name: 'INT. LOBBY – DAY',
        code: 'S01-S02',
        description: 'Jack checks in and is led to Ullman.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0062.jpg',
        children: ['SHOT_3', 'SHOT_4'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_3': {
        id: 'SC_3',
        type: 'scene',
        name: "INT. ULLMAN'S OFFICE – DAY",
        code: 'S01-S03',
        description: 'Meet Ullman and Watson; caretaker interview.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0062.jpg',
        children: ['SHOT_5', 'SHOT_6', 'SHOT_7'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_4': {
        id: 'SC_4',
        type: 'scene',
        name: 'EXT/INT. BOULDER APARTMENT – DAY',
        code: 'S01-S04',
        description: 'Danny and Wendy talk about the move; Tony ‘speaks.’',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0048.jpg',
        children: ['SHOT_8', 'SHOT_9'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_5': {
        id: 'SC_5',
        type: 'scene',
        name: "INT. ULLMAN'S OFFICE – DAY (CONT.)",
        code: 'S01-S05',
        description: 'Clarify duties; agree on arrival for Closing Day.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0022.jpg',
        children: ['SHOT_10', 'SHOT_11'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_6': {
        id: 'SC_6',
        type: 'scene',
        name: 'EXT. MOUNTAINS/OVERLOOK – DAY',
        code: 'S02-S06',
        description: 'The Torrance family arrives at the Overlook.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0088.jpg',
        children: ['SHOT_12', 'SHOT_13'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_7': {
        id: 'SC_7',
        type: 'scene',
        name: 'INT. LOBBY – DAY',
        code: 'S02-S07',
        description: 'Ullman/Watson prepare to close; greet the Torrances.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0037.jpg',
        children: ['SHOT_14', 'SHOT_15', 'SHOT_16'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_8': {
        id: 'SC_8',
        type: 'scene',
        name: 'INT. KITCHEN – DAY',
        code: 'S02-S08',
        description: 'Halloran gives Wendy and Danny a kitchen tour; bonds with Danny.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0039.jpg',
        children: ['SHOT_17', 'SHOT_18', 'SHOT_19'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_9': {
        id: 'SC_9',
        type: 'scene',
        name: 'INT. WALK-IN FREEZER – DAY',
        code: 'S02-S09',
        description: 'Supplies for the winter; caretaker logistics.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0035.jpg',
        children: ['SHOT_20', 'SHOT_21'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_10': {
        id: 'SC_10',
        type: 'scene',
        name: 'INT. KITCHEN (SHINING TALK) – DAY',
        code: 'S02-S10',
        description: 'Halloran explains the ‘shining’ to Danny and hints at the hotel’s traces.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0013.jpg',
        children: ['SHOT_22', 'SHOT_23'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_11': {
        id: 'SC_11',
        type: 'scene',
        name: 'INT. KITCHEN/CORRIDORS – DAY',
        code: 'S02-S11',
        description: 'Warning about Room 237 — strictly off limits.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0039.jpg',
        children: ['SHOT_24', 'SHOT_25'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_12': {
        id: 'SC_12',
        type: 'scene',
        name: 'INT. GAMES ROOM – DAY',
        code: 'S02-S12',
        description: 'Danny sees the Grady twins — first sinister vision.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0013.jpg',
        children: ['SHOT_26', 'SHOT_27', 'SHOT_28'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_13': {
        id: 'SC_13',
        type: 'scene',
        name: 'INT. CARETAKER APARTMENT – DAY',
        code: 'S02-S13',
        description: 'The family is shown their winter quarters.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0088.jpg',
        children: ['SHOT_29', 'SHOT_30'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_14': {
        id: 'SC_14',
        type: 'scene',
        name: 'INT. LOBBY/CORRIDORS – DAY',
        code: 'S03-S14',
        description: 'Wendy runs the household; chores continue.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0082.jpg',
        children: ['SHOT_31', 'SHOT_32', 'SHOT_33'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_15': {
        id: 'SC_15',
        type: 'scene',
        name: 'INT. CARETAKER APT – LATE MORNING',
        code: 'S03-S15',
        description: 'Breakfast in bed for Jack — late schedule, stalled writing.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0082.jpg',
        children: ['SHOT_34', 'SHOT_35'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_16': {
        id: 'SC_16',
        type: 'scene',
        name: 'INT. KITCHEN ↔ LOUNGE – DAY',
        code: 'S03-S16',
        description: 'Danny rides corridors; signature tracking run.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0049.jpg',
        children: ['SHOT_36', 'SHOT_37'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_17': {
        id: 'SC_17',
        type: 'scene',
        name: 'EXT. HEDGE MAZE – DAY',
        code: 'S03-S17',
        description: 'Wendy and Danny explore the maze; foreshadowing entrapment.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0081.jpg',
        children: ['SHOT_38', 'SHOT_39'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_18': {
        id: 'SC_18',
        type: 'scene',
        name: 'INT. COLORADO LOUNGE – DAY',
        code: 'S03-S18',
        description: 'Jack ‘writes,’ irritable and empty; isolation deepens.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0067.jpg',
        children: ['SHOT_40', 'SHOT_41', 'SHOT_42'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_19': {
        id: 'SC_19',
        type: 'scene',
        name: 'INT. 2ND-FLOOR CORRIDORS – DAY',
        code: 'S04-S19',
        description: 'Danny reaches for the knob — locked; visions of the twins.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0012.jpg',
        children: ['SHOT_43', 'SHOT_44'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_20': {
        id: 'SC_20',
        type: 'scene',
        name: 'INT. LOUNGE – NIGHT',
        code: 'S04-S20',
        description: 'Atmospheric beats imply a presence without direct contact.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0088.jpg',
        children: ['SHOT_45', 'SHOT_46', 'SHOT_47'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_21': {
        id: 'SC_21',
        type: 'scene',
        name: 'CARD: THURSDAY / EXT. HOTEL – DAY',
        code: 'S05-S21',
        description: 'Wendy and Danny play outside; Jack watches, detached.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0088.jpg',
        children: ['SHOT_48', 'SHOT_49'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_22': {
        id: 'SC_22',
        type: 'scene',
        name: 'CARD: SATURDAY / INT. SWITCHBOARD – DAY',
        code: 'S05-S22',
        description: 'Phone lines are dead; Wendy reaches park rangers on radio.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0064.jpg',
        children: ['SHOT_50', 'SHOT_51', 'SHOT_52'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_23': {
        id: 'SC_23',
        type: 'scene',
        name: 'INT. OFFICE (RADIO) – DAY',
        code: 'S05-S23',
        description: 'Ranger advises they keep the radio on — storm cuts them off.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0034.jpg',
        children: ['SHOT_53', 'SHOT_54'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_24': {
        id: 'SC_24',
        type: 'scene',
        name: 'INT. APARTMENT – DAY (TV)',
        code: 'S06-S24',
        description: 'Domestic beat with TV; sense of prolonged lull.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0068.jpg',
        children: ['SHOT_55', 'SHOT_56'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_25': {
        id: 'SC_25',
        type: 'scene',
        name: 'INT. APARTMENT (FATHER/SON) – DAY',
        code: 'S06-S25',
        description: 'Danny asks Jack: “You wouldn’t hurt us, would you?”',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0034.jpg',
        children: ['SHOT_57', 'SHOT_58'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_26': {
        id: 'SC_26',
        type: 'scene',
        name: 'INT. 2ND-FLOOR CORRIDORS – DAY',
        code: 'S07-S26',
        description: 'An unseen ‘pass’ draws Danny to 237.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0078.jpg',
        children: ['SHOT_59', 'SHOT_60', 'SHOT_61'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_27': {
        id: 'SC_27',
        type: 'scene',
        name: 'INT. LOUNGE (NIGHTMARE) – DAY',
        code: 'S07-S27',
        description: 'Jack wakes from a nightmare; Wendy rushes in; Danny appears bruised.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0081.jpg',
        children: ['SHOT_62', 'SHOT_63'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_28': {
        id: 'SC_28',
        type: 'scene',
        name: 'INT. GOLD ROOM (BAR) – NIGHT',
        code: 'S07-S28',
        description: 'Jack ‘drinks’ with Lloyd — obsession takes hold.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0021.jpg',
        children: ['SHOT_64', 'SHOT_65'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_29': {
        id: 'SC_29',
        type: 'scene',
        name: 'INT. ROOM 237 (BATH) – NIGHT',
        code: 'S08-S29',
        description: 'Jack enters; encounter with the ‘woman’ — transformation beat.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0069.jpg',
        children: ['SHOT_66', 'SHOT_67'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_30': {
        id: 'SC_30',
        type: 'scene',
        name: 'INT. CORRIDOR OUTSIDE 237 – NIGHT',
        code: 'S08-S30',
        description: 'Jack retreats and locks 237.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0081.jpg',
        children: ['SHOT_68', 'SHOT_69', 'SHOT_70'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_31': {
        id: 'SC_31',
        type: 'scene',
        name: 'INT. APARTMENT – NIGHT',
        code: 'S08-S31',
        description: 'Jack lies to Wendy: he saw ‘nothing’ in 237.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0081.jpg',
        children: ['SHOT_71', 'SHOT_72'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_32': {
        id: 'SC_32',
        type: 'scene',
        name: 'INT. APARTMENT (TUCK-IN) – NIGHT',
        code: 'S09-S32',
        description: 'Wendy tucks in Danny/Tony and goes to find Jack.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0089.jpg',
        children: ['SHOT_73', 'SHOT_74'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_33': {
        id: 'SC_33',
        type: 'scene',
        name: 'INT. COLORADO LOUNGE – NIGHT',
        code: 'S09-S33',
        description: 'Wendy discovers the manuscript: ‘ALL WORK AND NO PLAY…’ on hundreds of pages.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0002.jpg',
        children: ['SHOT_75', 'SHOT_76', 'SHOT_77'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_34': {
        id: 'SC_34',
        type: 'scene',
        name: 'INT. GRAND STAIR – NIGHT',
        code: 'S09-S34',
        description: 'Showdown with Jack; she fends him off with the bat and drops him.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0030.jpg',
        children: ['SHOT_78', 'SHOT_79'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_35': {
        id: 'SC_35',
        type: 'scene',
        name: 'INT. KITCHEN / FOOD STORE – NIGHT',
        code: 'S09-S35',
        description: 'Wendy drags Jack to the pantry and locks him in.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0041.jpg',
        children: ['SHOT_80', 'SHOT_81'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_36': {
        id: 'SC_36',
        type: 'scene',
        name: 'INT. KITCHEN (OUTSIDE PANTRY) – NIGHT',
        code: 'S09-S36',
        description: 'Wendy grabs a knife, sobbing, realizing the stakes.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0081.jpg',
        children: ['SHOT_82', 'SHOT_83', 'SHOT_84'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_37': {
        id: 'SC_37',
        type: 'scene',
        name: 'INT. FOOD STORE (JACK PLEADS) – NIGHT',
        code: 'S09-S37',
        description: 'Jack pleads to be released; taunts her to check the snowcat and radio.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0066.jpg',
        children: ['SHOT_85', 'SHOT_86'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SC_38': {
        id: 'SC_38',
        type: 'scene',
        name: 'EXT. PORCH → INT. GARAGE – DAY',
        code: 'S09-S38',
        description: 'Wendy forces through snow; finds the sabotaged snowcat and ripped-out radio parts.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0061.jpg',
        children: ['SHOT_87', 'SHOT_88', 'SHOT_89'],
        duration: 0,
        studio: 'Warner Bros.'
    },
    'SHOT_1': {
        id: 'SHOT_1',
        type: 'shot',
        name: 'Shot 2',
        code: 'S01-S01-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0035.jpg',
        duration: 168,
        studio: 'Warner Bros.'
    },
    'SHOT_2': {
        id: 'SHOT_2',
        type: 'shot',
        name: 'Shot 3',
        code: 'S01-S01-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0041.jpg',
        duration: 133,
        studio: 'Warner Bros.'
    },
    'SHOT_3': {
        id: 'SHOT_3',
        type: 'shot',
        name: 'Shot 4',
        code: 'S01-S02-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0079.jpg',
        duration: 104,
        studio: 'Warner Bros.'
    },
    'SHOT_4': {
        id: 'SHOT_4',
        type: 'shot',
        name: 'Shot 5',
        code: 'S01-S02-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0037.jpg',
        duration: 138,
        studio: 'Warner Bros.'
    },
    'SHOT_5': {
        id: 'SHOT_5',
        type: 'shot',
        name: 'Shot 6',
        code: 'S01-S03-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0031.jpg',
        duration: 111,
        studio: 'Warner Bros.'
    },
    'SHOT_6': {
        id: 'SHOT_6',
        type: 'shot',
        name: 'Shot 7',
        code: 'S01-S03-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0048.jpg',
        duration: 141,
        studio: 'Warner Bros.'
    },
    'SHOT_7': {
        id: 'SHOT_7',
        type: 'shot',
        name: 'Shot 8',
        code: 'S01-S03-SH3',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0030.jpg',
        duration: 178,
        studio: 'Warner Bros.'
    },
    'SHOT_8': {
        id: 'SHOT_8',
        type: 'shot',
        name: 'Shot 9',
        code: 'S01-S04-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0036.jpg',
        duration: 119,
        studio: 'Warner Bros.'
    },
    'SHOT_9': {
        id: 'SHOT_9',
        type: 'shot',
        name: 'Shot 10',
        code: 'S01-S04-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0019.jpg',
        duration: 138,
        studio: 'Warner Bros.'
    },
    'SHOT_10': {
        id: 'SHOT_10',
        type: 'shot',
        name: 'Shot 11',
        code: 'S01-S05-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0034.jpg',
        duration: 123,
        studio: 'Warner Bros.'
    },
    'SHOT_11': {
        id: 'SHOT_11',
        type: 'shot',
        name: 'Shot 12',
        code: 'S01-S05-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0065.jpg',
        duration: 136,
        studio: 'Warner Bros.'
    },
    'SHOT_12': {
        id: 'SHOT_12',
        type: 'shot',
        name: 'Shot 13',
        code: 'S02-S06-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0013.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_13': {
        id: 'SHOT_13',
        type: 'shot',
        name: 'Shot 14',
        code: 'S02-S06-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0013.jpg',
        duration: 130,
        studio: 'Warner Bros.'
    },
    'SHOT_14': {
        id: 'SHOT_14',
        type: 'shot',
        name: 'Shot 15',
        code: 'S02-S07-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0088.jpg',
        duration: 111,
        studio: 'Warner Bros.'
    },
    'SHOT_15': {
        id: 'SHOT_15',
        type: 'shot',
        name: 'Shot 16',
        code: 'S02-S07-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0083.jpg',
        duration: 176,
        studio: 'Warner Bros.'
    },
    'SHOT_16': {
        id: 'SHOT_16',
        type: 'shot',
        name: 'Shot 17',
        code: 'S02-S07-SH3',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0057.jpg',
        duration: 113,
        studio: 'Warner Bros.'
    },
    'SHOT_17': {
        id: 'SHOT_17',
        type: 'shot',
        name: 'Shot 18',
        code: 'S02-S08-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0018.jpg',
        duration: 113,
        studio: 'Warner Bros.'
    },
    'SHOT_18': {
        id: 'SHOT_18',
        type: 'shot',
        name: 'Shot 19',
        code: 'S02-S08-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0013.jpg',
        duration: 135,
        studio: 'Warner Bros.'
    },
    'SHOT_19': {
        id: 'SHOT_19',
        type: 'shot',
        name: 'Shot 20',
        code: 'S02-S08-SH3',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0088.jpg',
        duration: 141,
        studio: 'Warner Bros.'
    },
    'SHOT_20': {
        id: 'SHOT_20',
        type: 'shot',
        name: 'Shot 21',
        code: 'S02-S09-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0081.jpg',
        duration: 118,
        studio: 'Warner Bros.'
    },
    'SHOT_21': {
        id: 'SHOT_21',
        type: 'shot',
        name: 'Shot 22',
        code: 'S02-S09-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0064.jpg',
        duration: 103,
        studio: 'Warner Bros.'
    },
    'SHOT_22': {
        id: 'SHOT_22',
        type: 'shot',
        name: 'Shot 23',
        code: 'S02-S10-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0078.jpg',
        duration: 178,
        studio: 'Warner Bros.'
    },
    'SHOT_23': {
        id: 'SHOT_23',
        type: 'shot',
        name: 'Shot 24',
        code: 'S02-S10-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0068.jpg',
        duration: 116,
        studio: 'Warner Bros.'
    },
    'SHOT_24': {
        id: 'SHOT_24',
        type: 'shot',
        name: 'Shot 25',
        code: 'S02-S11-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0081.jpg',
        duration: 108,
        studio: 'Warner Bros.'
    },
    'SHOT_25': {
        id: 'SHOT_25',
        type: 'shot',
        name: 'Shot 26',
        code: 'S02-S11-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0089.jpg',
        duration: 113,
        studio: 'Warner Bros.'
    },
    'SHOT_26': {
        id: 'SHOT_26',
        type: 'shot',
        name: 'Shot 27',
        code: 'S02-S12-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0081.jpg',
        duration: 175,
        studio: 'Warner Bros.'
    },
    'SHOT_27': {
        id: 'SHOT_27',
        type: 'shot',
        name: 'Shot 28',
        code: 'S02-S12-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0088.jpg',
        duration: 156,
        studio: 'Warner Bros.'
    },
    'SHOT_28': {
        id: 'SHOT_28',
        type: 'shot',
        name: 'Shot 29',
        code: 'S02-S12-SH3',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0081.jpg',
        duration: 107,
        studio: 'Warner Bros.'
    },
    'SHOT_29': {
        id: 'SHOT_29',
        type: 'shot',
        name: 'Shot 30',
        code: 'S02-S13-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0081.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_30': {
        id: 'SHOT_30',
        type: 'shot',
        name: 'Shot 31',
        code: 'S02-S13-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0081.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_31': {
        id: 'SHOT_31',
        type: 'shot',
        name: 'Shot 32',
        code: 'S03-S14-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0081.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_32': {
        id: 'SHOT_32',
        type: 'shot',
        name: 'Shot 33',
        code: 'S03-S14-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0081.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_33': {
        id: 'SHOT_33',
        type: 'shot',
        name: 'Shot 34',
        code: 'S03-S14-SH3',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0081.jpg',
        duration: 107,
        studio: 'Warner Bros.'
    },
    'SHOT_34': {
        id: 'SHOT_34',
        type: 'shot',
        name: 'Shot 35',
        code: 'S03-S15-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0081.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_35': {
        id: 'SHOT_35',
        type: 'shot',
        name: 'Shot 36',
        code: 'S03-S15-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0081.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_36': {
        id: 'SHOT_36',
        type: 'shot',
        name: 'Shot 37',
        code: 'S03-S16-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0081.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_37': {
        id: 'SHOT_37',
        type: 'shot',
        name: 'Shot 38',
        code: 'S03-S16-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0081.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_38': {
        id: 'SHOT_38',
        type: 'shot',
        name: 'Shot 39',
        code: 'S03-S17-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0081.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_39': {
        id: 'SHOT_39',
        type: 'shot',
        name: 'Shot 40',
        code: 'S03-S17-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0081.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_40': {
        id: 'SHOT_40',
        type: 'shot',
        name: 'Shot 41',
        code: 'S03-S18-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0081.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_41': {
        id: 'SHOT_41',
        type: 'shot',
        name: 'Shot 42',
        code: 'S03-S18-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0081.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_42': {
        id: 'SHOT_42',
        type: 'shot',
        name: 'Shot 43',
        code: 'S03-S18-SH3',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0081.jpg',
        duration: 107,
        studio: 'Warner Bros.'
    },
    'SHOT_43': {
        id: 'SHOT_43',
        type: 'shot',
        name: 'Shot 44',
        code: 'S04-S19-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0043.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_44': {
        id: 'SHOT_44',
        type: 'shot',
        name: 'Shot 45',
        code: 'S04-S19-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0044.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_45': {
        id: 'SHOT_45',
        type: 'shot',
        name: 'Shot 46',
        code: 'S04-S20-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0045.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_46': {
        id: 'SHOT_46',
        type: 'shot',
        name: 'Shot 47',
        code: 'S04-S20-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0046.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_47': {
        id: 'SHOT_47',
        type: 'shot',
        name: 'Shot 48',
        code: 'S04-S20-SH3',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0047.jpg',
        duration: 107,
        studio: 'Warner Bros.'
    },
    'SHOT_48': {
        id: 'SHOT_48',
        type: 'shot',
        name: 'Shot 49',
        code: 'S05-S21-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0050.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_49': {
        id: 'SHOT_49',
        type: 'shot',
        name: 'Shot 50',
        code: 'S05-S21-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0051.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_50': {
        id: 'SHOT_50',
        type: 'shot',
        name: 'Shot 51',
        code: 'S05-S22-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0052.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_51': {
        id: 'SHOT_51',
        type: 'shot',
        name: 'Shot 52',
        code: 'S05-S22-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0054.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_52': {
        id: 'SHOT_52',
        type: 'shot',
        name: 'Shot 53',
        code: 'S05-S22-SH3',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0055.jpg',
        duration: 107,
        studio: 'Warner Bros.'
    },
    'SHOT_53': {
        id: 'SHOT_53',
        type: 'shot',
        name: 'Shot 54',
        code: 'S05-S23-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0056.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_54': {
        id: 'SHOT_54',
        type: 'shot',
        name: 'Shot 55',
        code: 'S05-S23-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0059.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_55': {
        id: 'SHOT_55',
        type: 'shot',
        name: 'Shot 56',
        code: 'S06-S24-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0060.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_56': {
        id: 'SHOT_56',
        type: 'shot',
        name: 'Shot 57',
        code: 'S06-S24-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0063.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_57': {
        id: 'SHOT_57',
        type: 'shot',
        name: 'Shot 58',
        code: 'S06-S25-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0070.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_58': {
        id: 'SHOT_58',
        type: 'shot',
        name: 'Shot 59',
        code: 'S06-S25-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0071.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_59': {
        id: 'SHOT_59',
        type: 'shot',
        name: 'Shot 60',
        code: 'S07-S26-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0072.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_60': {
        id: 'SHOT_60',
        type: 'shot',
        name: 'Shot 61',
        code: 'S07-S26-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0073.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_61': {
        id: 'SHOT_61',
        type: 'shot',
        name: 'Shot 62',
        code: 'S07-S26-SH3',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0074.jpg',
        duration: 107,
        studio: 'Warner Bros.'
    },
    'SHOT_62': {
        id: 'SHOT_62',
        type: 'shot',
        name: 'Shot 63',
        code: 'S07-S27-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0075.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_63': {
        id: 'SHOT_63',
        type: 'shot',
        name: 'Shot 64',
        code: 'S07-S27-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0076.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_64': {
        id: 'SHOT_64',
        type: 'shot',
        name: 'Shot 65',
        code: 'S07-S28-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0077.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_65': {
        id: 'SHOT_65',
        type: 'shot',
        name: 'Shot 66',
        code: 'S07-S28-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0080.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_66': {
        id: 'SHOT_66',
        type: 'shot',
        name: 'Shot 67',
        code: 'S08-S29-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0001.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_67': {
        id: 'SHOT_67',
        type: 'shot',
        name: 'Shot 68',
        code: 'S08-S29-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0003.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_68': {
        id: 'SHOT_68',
        type: 'shot',
        name: 'Shot 69',
        code: 'S08-S30-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0004.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_69': {
        id: 'SHOT_69',
        type: 'shot',
        name: 'Shot 70',
        code: 'S08-S30-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0005.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_70': {
        id: 'SHOT_70',
        type: 'shot',
        name: 'Shot 71',
        code: 'S08-S30-SH3',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0006.jpg',
        duration: 107,
        studio: 'Warner Bros.'
    },
    'SHOT_71': {
        id: 'SHOT_71',
        type: 'shot',
        name: 'Shot 72',
        code: 'S08-S31-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0007.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_72': {
        id: 'SHOT_72',
        type: 'shot',
        name: 'Shot 73',
        code: 'S08-S31-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0008.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_73': {
        id: 'SHOT_73',
        type: 'shot',
        name: 'Shot 74',
        code: 'S09-S32-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0010.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_74': {
        id: 'SHOT_74',
        type: 'shot',
        name: 'Shot 75',
        code: 'S09-S32-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0011.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_75': {
        id: 'SHOT_75',
        type: 'shot',
        name: 'Shot 76',
        code: 'S09-S33-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0014.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_76': {
        id: 'SHOT_76',
        type: 'shot',
        name: 'Shot 77',
        code: 'S09-S33-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0015.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_77': {
        id: 'SHOT_77',
        type: 'shot',
        name: 'Shot 78',
        code: 'S09-S33-SH3',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0016.jpg',
        duration: 107,
        studio: 'Warner Bros.'
    },
    'SHOT_78': {
        id: 'SHOT_78',
        type: 'shot',
        name: 'Shot 79',
        code: 'S09-S34-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0017.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_79': {
        id: 'SHOT_79',
        type: 'shot',
        name: 'Shot 80',
        code: 'S09-S34-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0020.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_80': {
        id: 'SHOT_80',
        type: 'shot',
        name: 'Shot 81',
        code: 'S09-S35-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0024.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_81': {
        id: 'SHOT_81',
        type: 'shot',
        name: 'Shot 82',
        code: 'S09-S35-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0025.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_82': {
        id: 'SHOT_82',
        type: 'shot',
        name: 'Shot 83',
        code: 'S09-S36-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0026.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_83': {
        id: 'SHOT_83',
        type: 'shot',
        name: 'Shot 84',
        code: 'S09-S36-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0027.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_84': {
        id: 'SHOT_84',
        type: 'shot',
        name: 'Shot 85',
        code: 'S09-S36-SH3',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0028.jpg',
        duration: 107,
        studio: 'Warner Bros.'
    },
    'SHOT_85': {
        id: 'SHOT_85',
        type: 'shot',
        name: 'Shot 86',
        code: 'S09-S37-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0029.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_86': {
        id: 'SHOT_86',
        type: 'shot',
        name: 'Shot 87',
        code: 'S09-S37-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0032.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_87': {
        id: 'SHOT_87',
        type: 'shot',
        name: 'Shot 88',
        code: 'S09-S38-SH1',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0038.jpg',
        duration: 170,
        studio: 'Warner Bros.'
    },
    'SHOT_88': {
        id: 'SHOT_88',
        type: 'shot',
        name: 'Shot 89',
        code: 'S09-S38-SH2',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0040.jpg',
        duration: 151,
        studio: 'Warner Bros.'
    },
    'SHOT_89': {
        id: 'SHOT_89',
        type: 'shot',
        name: 'Shot 90',
        code: 'S09-S38-SH3',
        description: 'A shot description.',
        image: 'https://alexandersokolov.com/continuity/thumbnails/shining_thumb_0042.jpg',
        duration: 107,
        studio: 'Warner Bros.'
    }
};