export const projectData = {
    PROJ_001: {
        id: 'PROJ_001',
        type: 'project',
        name: 'Cyberpunk City',
        code: 'CP-2077',
        description: 'A sprawling metropolis of the future, filled with high-tech wonders and dark secrets.',
        image: 'https://picsum.photos/seed/PROJ_001/400/225',
        children: ['SEQ_001', 'SEQ_002', 'SEQ_003', 'SEQ_004', 'SEQ_005'],
    },
    SEQ_001: {
        id: 'SEQ_001',
        type: 'sequence',
        name: 'The Heist',
        code: 'S01',
        description: 'The introductory sequence where the crew plans and executes a high-stakes corporate theft.',
        image: 'https://picsum.photos/seed/SEQ_001/400/225',
        children: ['SC_001', 'SC_002', 'SC_003'],
        duration: 0,
    },
    SEQ_002: {
        id: 'SEQ_002',
        type: 'sequence',
        name: 'Street Chase',
        code: 'S02',
        description: 'A fast-paced chase through the neon-lit streets of the city.',
        image: 'https://picsum.photos/seed/SEQ_002/400/225',
        children: ['SC_004', 'SC_005', 'SC_010'],
        duration: 0,
    },
    SEQ_003: {
        id: 'SEQ_003',
        type: 'sequence',
        name: 'Rooftop Confrontation',
        code: 'S03',
        description: 'A dramatic showdown on the rain-slicked roof of a skyscraper.',
        image: 'https://picsum.photos/seed/SEQ_003/400/225',
        children: ['SC_006', 'SC_011', 'SC_012'],
        duration: 0,
    },
    SEQ_004: {
        id: 'SEQ_004',
        type: 'sequence',
        name: 'The Aftermath',
        code: 'S04',
        description: 'Dealing with the consequences of the heist.',
        image: 'https://picsum.photos/seed/SEQ_004/400/225',
        children: ['SC_007', 'SC_013', 'SC_014'],
    },
    SEQ_005: {
        id: 'SEQ_005',
        type: 'sequence',
        name: 'Final Escape',
        code: 'S05',
        description: 'The final escape from the city.',
        image: 'https://picsum.photos/seed/SEQ_005/400/225',
        children: ['SC_008', 'SC_009', 'SC_015'],
    },
    SC_001: {
        id: 'SC_001',
        type: 'scene',
        name: 'The Briefing',
        code: 'S01-SC01',
        description: 'The team gathers to go over the plan.',
        image: 'https://picsum.photos/seed/SC_001/400/225',
        children: ['SHOT_001', 'SHOT_002', 'SHOT_004', 'SHOT_005'],
        duration: 0,
    },
    SC_002: {
        id: 'SC_002',
        type: 'scene',
        name: 'Infiltration',
        code: 'S01-SC02',
        description: 'The team bypasses security and enters the tower.',
        image: 'https://picsum.photos/seed/SC_002/400/225',
        children: ['SHOT_003', 'SHOT_006', 'SHOT_007', 'SHOT_008'],
        duration: 0,
    },
    SC_003: {
        id: 'SC_003',
        type: 'scene',
        name: 'The Vault',
        code: 'S01-SC03',
        description: 'The team cracks the vault and secures the package.',
        image: 'https://picsum.photos/seed/SC_003/400/225',
        children: ['SHOT_009', 'SHOT_010', 'SHOT_011', 'SHOT_012'],
        duration: 0,
    },
    SC_004: {
        id: 'SC_004',
        type: 'scene',
        name: 'Market Escape',
        code: 'S02-SC01',
        description: 'The team flees through a crowded market.',
        image: 'https://picsum.photos/seed/SC_004/400/225',
        children: ['SHOT_013', 'SHOT_014', 'SHOT_015', 'SHOT_016'],
        duration: 0,
    },
    SC_005: {
        id: 'SC_005',
        type: 'scene',
        name: 'Highway Battle',
        code: 'S02-SC02',
        description: 'A gunfight erupts on the elevated highway.',
        image: 'https://picsum.photos/seed/SC_005/400/225',
        children: ['SHOT_017', 'SHOT_018', 'SHOT_019', 'SHOT_020'],
        duration: 0,
    },
    SC_006: {
        id: 'SC_006',
        type: 'scene',
        name: 'The Standoff',
        code: 'S03-SC01',
        description: 'The protagonist confronts the antagonist.',
        image: 'https://picsum.photos/seed/SC_006/400/225',
        children: ['SHOT_021', 'SHOT_022', 'SHOT_023', 'SHOT_024'],
        duration: 0,
    },
    SC_007: {
        id: 'SC_007',
        type: 'scene',
        name: 'Safehouse Debrief',
        code: 'S04-SC01',
        description: 'The crew regroups at a hidden safehouse.',
        image: 'https://picsum.photos/seed/SC_007/400/225',
        children: ['SHOT_025', 'SHOT_026', 'SHOT_027', 'SHOT_028'],
        duration: 0,
    },
    SC_008: {
        id: 'SC_008',
        type: 'scene',
        name: 'Mag-Lev Station',
        code: 'S05-SC01',
        description: 'A tense scene at the city\'s main transport hub.',
        image: 'https://picsum.photos/seed/SC_008/400/225',
        children: ['SHOT_029', 'SHOT_030', 'SHOT_031', 'SHOT_032'],
        duration: 0,
    },
    SC_009: {
        id: 'SC_009',
        type: 'scene',
        name: 'Leaving the City',
        code: 'S05-SC02',
        description: 'The final shot of the train leaving the city limits.',
        image: 'https://picsum.photos/seed/SC_009/400/225',
        children: ['SHOT_033', 'SHOT_034', 'SHOT_035', 'SHOT_036'],
        duration: 0,
    },
    SC_010: {
        id: 'SC_010',
        type: 'scene',
        name: 'Freeway Overpass',
        code: 'S02-SC03',
        description: 'A chase sequence on a freeway overpass.',
        image: 'https://picsum.photos/seed/SC_010/400/225',
        children: ['SHOT_037', 'SHOT_038', 'SHOT_039', 'SHOT_040'],
        duration: 0,
    },
    SC_011: {
        id: 'SC_011',
        type: 'scene',
        name: 'Helipad Escape',
        code: 'S03-SC02',
        description: 'The protagonist escapes in a helicopter.',
        image: 'https://picsum.photos/seed/SC_011/400/225',
        children: ['SHOT_041', 'SHOT_042', 'SHOT_043', 'SHOT_044'],
        duration: 0,
    },
    SC_012: {
        id: 'SC_012',
        type: 'scene',
        name: 'Rooftop Garden',
        code: 'S03-SC03',
        description: 'A quiet moment in a rooftop garden.',
        image: 'https://picsum.photos/seed/SC_012/400/225',
        children: ['SHOT_045', 'SHOT_046', 'SHOT_047', 'SHOT_048'],
        duration: 0,
    },
    SC_013: {
        id: 'SC_013',
        type: 'scene',
        name: 'Interrogation Room',
        code: 'S04-SC02',
        description: 'A tense interrogation scene.',
        image: 'https://picsum.photos/seed/SC_013/400/225',
        children: ['SHOT_049', 'SHOT_050', 'SHOT_051', 'SHOT_052'],
        duration: 0,
    },
    SC_014: {
        id: 'SC_014',
        type: 'scene',
        name: 'Evidence Board',
        code: 'S04-SC03',
        description: 'The team pieces together the clues.',
        image: 'https://picsum.photos/seed/SC_014/400/225',
        children: ['SHOT_053', 'SHOT_054', 'SHOT_055', 'SHOT_056'],
        duration: 0,
    },
    SC_015: {
        id: 'SC_015',
        type: 'scene',
        name: 'Border Crossing',
        code: 'S05-SC03',
        description: 'The final hurdle in the escape.',
        image: 'https://picsum.photos/seed/SC_015/400/225',
        children: ['SHOT_057', 'SHOT_058', 'SHOT_059', 'SHOT_060'],
    },
    SHOT_001: {
        id: 'SHOT_001',
        type: 'shot',
        name: 'CU on Datachip',
        code: 'S01-SC01-SH01',
        description: 'A wide establishing shot of the futuristic city skyline at dawn.',
        image: 'https://picsum.photos/seed/SHOT_001/400/225',
        duration: 120,
    },
    SHOT_002: {
        id: 'SHOT_002',
        type: 'shot',
        name: 'Wide of Team',
        code: 'S01-SC01-SH02',
        description: 'A medium shot of the main character waking up in their apartment.',
        image: 'https://picsum.photos/seed/SHOT_002/400/225',
        duration: 180,
    },
    SHOT_003: {
        id: 'SHOT_003',
        type: 'shot',
        name: 'Tracking Shot',
        code: 'S01-SC02-SH01',
        description: 'A close-up on a holographic interface displaying critical information.',
        image: 'https://picsum.photos/seed/SHOT_003/400/225',
        duration: 90,
    },
    SHOT_004: {
        id: 'SHOT_004',
        type: 'shot',
        name: 'Overhead of map',
        code: 'S01-SC01-SH03',
        description: 'A tracking shot following a character through a bustling market.',
        image: 'https://picsum.photos/seed/SHOT_004/400/225',
        duration: 240,
    },
    SHOT_005: {
        id: 'SHOT_005',
        type: 'shot',
        name: 'Reaction shot',
        code: 'S01-SC01-SH04',
        description: 'An over-the-shoulder shot of the antagonist observing the city.',
        image: 'https://picsum.photos/seed/SHOT_005/400/225',
        duration: 150,
    },
    SHOT_006: {
        id: 'SHOT_006',
        type: 'shot',
        name: 'Security camera POV',
        code: 'S01-SC02-SH02',
        description: 'A shot from the perspective of a security camera.',
        image: 'https://picsum.photos/seed/SHOT_006/400/225',
        duration: 60,
    },
    SHOT_007: {
        id: 'SHOT_007',
        type: 'shot',
        name: 'Close up on keypad',
        code: 'S01-SC02-SH03',
        description: 'A close-up of the netrunner hacking a keypad.',
        image: 'https://picsum.photos/seed/SHOT_007/400/225',
        duration: 75,
    },
    SHOT_008: {
        id: 'SHOT_008',
        type: 'shot',
        name: 'Door opening',
        code: 'S01-SC02-SH04',
        description: 'A shot of a heavy security door sliding open.',
        image: 'https://picsum.photos/seed/SHOT_008/400/225',
        duration: 100,
    },
    SHOT_009: {
        id: 'SHOT_009',
        type: 'shot',
        name: 'Laser grid deactivates',
        code: 'S01-SC03-SH01',
        description: 'A shot of a laser grid deactivating.',
        image: 'https://picsum.photos/seed/SHOT_009/400/225',
        duration: 50,
    },
    SHOT_010: {
        id: 'SHOT_010',
        type: 'shot',
        name: 'Grabbing the package',
        code: 'S01-SC03-SH02',
        description: 'A close-up of the crew member grabbing the package.',
        image: 'https://picsum.photos/seed/SHOT_010/400/225',
        duration: 80,
    },
    SHOT_011: {
        id: 'SHOT_011',
        type: 'shot',
        name: 'Alarm blares',
        code: 'S01-SC03-SH03',
        description: 'A shot of a red alarm light flashing.',
        image: 'https://picsum.photos/seed/SHOT_011/400/225',
        duration: 40,
    },
    SHOT_012: {
        id: 'SHOT_012',
        type: 'shot',
        name: 'Running out of the vault',
        code: 'S01-SC03-SH04',
        description: 'A shot of the team running out of the vault.',
        image: 'https://picsum.photos/seed/SHOT_012/400/225',
        duration: 110,
    },
    SHOT_013: {
        id: 'SHOT_013',
        type: 'shot',
        name: 'Knocking over a fruit stand',
        code: 'S02-SC01-SH01',
        description: 'A shot of the team knocking over a fruit stand.',
        image: 'https://picsum.photos/seed/SHOT_013/400/225',
        duration: 95,
    },
    SHOT_014: {
        id: 'SHOT_014',
        type: 'shot',
        name: 'Jumping over a car',
        code: 'S02-SC01-SH02',
        description: 'A shot of the protagonist jumping over a car.',
        image: 'https://picsum.photos/seed/SHOT_014/400/225',
        duration: 130,
    },
    SHOT_015: {
        id: 'SHOT_015',
        type: 'shot',
        name: 'Sliding under a gate',
        code: 'S02-SC01-SH03',
        description: 'A shot of the protagonist sliding under a closing gate.',
        image: 'https://picsum.photos/seed/SHOT_015/400/225',
        duration: 70,
    },
    SHOT_016: {
        id: 'SHOT_016',
        type: 'shot',
        name: 'Looking back at pursuers',
        code: 'S02-SC01-SH04',
        description: 'A shot of the protagonist looking back at their pursuers.',
        image: 'https://picsum.photos/seed/SHOT_016/400/225',
        duration: 85,
    },
    SHOT_017: {
        id: 'SHOT_017',
        type: 'shot',
        name: 'Car explosion',
        code: 'S02-SC02-SH01',
        description: 'A shot of a car exploding on the highway.',
        image: 'https://picsum.photos/seed/SHOT_017/400/225',
        duration: 160,
    },
    SHOT_018: {
        id: 'SHOT_018',
        type: 'shot',
        name: 'Shooting out a tire',
        code: 'S02-SC02-SH02',
        description: 'A close-up of a tire being shot out.',
        image: 'https://picsum.photos/seed/SHOT_018/400/225',
        duration: 55,
    },
    SHOT_019: {
        id: 'SHOT_019',
        type: 'shot',
        name: 'Jumping to another car',
        code: 'S02-SC02-SH03',
        description: 'A shot of the protagonist jumping from one car to another.',
        image: 'https://picsum.photos/seed/SHOT_019/400/225',
        duration: 140,
    },
    SHOT_020: {
        id: 'SHOT_020',
        type: 'shot',
        name: 'Helicopter flying overhead',
        code: 'S02-SC02-SH04',
        description: 'A shot of a helicopter flying overhead.',
        image: 'https://picsum.photos/seed/SHOT_020/400/225',
        duration: 115,
    },
    SHOT_021: {
        id: 'SHOT_021',
        type: 'shot',
        name: 'Drawing weapons',
        code: 'S03-SC01-SH01',
        description: 'A close-up of the protagonist and antagonist drawing their weapons.',
        image: 'https://picsum.photos/seed/SHOT_021/400/225',
        duration: 90,
    },
    SHOT_022: {
        id: 'SHOT_022',
        type: 'shot',
        name: 'Intense staredown',
        code: 'S03-SC01-SH02',
        description: 'A shot of an intense staredown between the two characters.',
        image: 'https://picsum.photos/seed/SHOT_022/400/225',
        duration: 105,
    },
    SHOT_023: {
        id: 'SHOT_023',
        type: 'shot',
        name: 'Rain pouring down',
        code: 'S03-SC01-SH03',
        description: 'A shot of rain pouring down on the rooftop.',
        image: 'https://picsum.photos/seed/SHOT_023/400/225',
        duration: 70,
    },
    SHOT_024: {
        id: 'SHOT_024',
        type: 'shot',
        name: 'First shot fired',
        code: 'S03-SC01-SH04',
        description: 'A shot of the first shot being fired.',
        image: 'https://picsum.photos/seed/SHOT_024/400/225',
        duration: 65,
    },
    SHOT_025: {
        id: 'SHOT_025',
        type: 'shot',
        name: 'Cleaning weapons',
        code: 'S04-SC01-SH01',
        description: 'A shot of the crew cleaning their weapons.',
        image: 'https://picsum.photos/seed/SHOT_025/400/225',
        duration: 80,
    },
    SHOT_026: {
        id: 'SHOT_026',
        type: 'shot',
        name: 'Tending to wounds',
        code: 'S04-SC01-SH02',
        description: 'A shot of a crew member tending to their wounds.',
        image: 'https://picsum.photos/seed/SHOT_026/400/225',
        duration: 95,
    },
    SHOT_027: {
        id: 'SHOT_027',
        type: 'shot',
        name: 'Looking at the score',
        code: 'S04-SC01-SH03',
        description: 'A shot of the crew looking at their score.',
        image: 'https://picsum.photos/seed/SHOT_027/400/225',
        duration: 110,
    },
    SHOT_028: {
        id: 'SHOT_028',
        type: 'shot',
        name: 'Planning the next move',
        code: 'S04-SC01-SH04',
        description: 'A shot of the crew planning their next move.',
        image: 'https://picsum.photos/seed/SHOT_028/400/225',
        duration: 125,
    },
    SHOT_029: {
        id: 'SHOT_029',
        type: 'shot',
        name: 'Buying tickets',
        code: 'S05-SC01-SH01',
        description: 'A shot of the protagonist buying tickets at the mag-lev station.',
        image: 'https://picsum.photos/seed/SHOT_029/400/225',
        duration: 70,
    },
    SHOT_030: {
        id: 'SHOT_030',
        type: 'shot',
        name: 'Spotting an enemy',
        code: 'S05-SC01-SH02',
        description: 'A shot of the protagonist spotting an enemy in the crowd.',
        image: 'https://picsum.photos/seed/SHOT_030/400/225',
        duration: 85,
    },
    SHOT_031: {
        id: 'SHOT_031',
        type: 'shot',
        name: 'Boarding the train',
        code: 'S05-SC01-SH03',
        description: 'A shot of the protagonist boarding the train.',
        image: 'https://picsum.photos/seed/SHOT_031/400/225',
        duration: 100,
    },
    SHOT_032: {
        id: 'SHOT_032',
        type: 'shot',
        name: 'Train doors closing',
        code: 'S05-SC01-SH04',
        description: 'A shot of the train doors closing.',
        image: 'https://picsum.photos/seed/SHOT_032/400/225',
        duration: 60,
    },
    SHOT_033: {
        id: 'SHOT_033',
        type: 'shot',
        name: 'Looking out the window',
        code: 'S05-SC02-SH01',
        description: 'A shot of the protagonist looking out the window as the train leaves the city.',
        image: 'https://picsum.photos/seed/SHOT_033/400/225',
        duration: 120,
    },
    SHOT_034: {
        id: 'SHOT_034',
        type: 'shot',
        name: 'City skyline receding',
        code: 'S05-SC02-SH02',
        description: 'A shot of the city skyline receding in the distance.',
        image: 'https://picsum.photos/seed/SHOT_034/400/225',
        duration: 150,
    },
    SHOT_035: {
        id: 'SHOT_035',
        type: 'shot',
        name: 'A sense of relief',
        code: 'S05-SC02-SH03',
        description: 'A close-up of the protagonist showing a sense of relief.',
        image: 'https://picsum.photos/seed/SHOT_035/400/225',
        duration: 90,
    },
    SHOT_036: {
        id: 'SHOT_036',
        type: 'shot',
        name: 'Fade to black',
        code: 'S05-SC02-SH04',
        description: 'The screen fades to black.',
        image: 'https://picsum.photos/seed/SHOT_036/400/225',
        duration: 30,
    },
    SHOT_037: {
        id: 'SHOT_037',
        type: 'shot',
        name: 'Dodging traffic',
        code: 'S02-SC03-SH01',
        description: 'A shot of the protagonist dodging traffic on the freeway overpass.',
        image: 'https://picsum.photos/seed/SHOT_037/400/225',
        duration: 110,
    },
    SHOT_038: {
        id: 'SHOT_038',
        type: 'shot',
        name: 'Jumping to a lower level',
        code: 'S02-SC03-SH02',
        description: 'A shot of the protagonist jumping to a lower level of the freeway.',
        image: 'https://picsum.photos/seed/SHOT_038/400/225',
        duration: 80,
    },
    SHOT_039: {
        id: 'SHOT_039',
        type: 'shot',
        name: 'Causing a pile-up',
        code: 'S02-SC03-SH03',
        description: 'A shot of a massive car pile-up.',
        image: 'https://picsum.photos/seed/SHOT_039/400/225',
        duration: 130,
    },
    SHOT_040: {
        id: 'SHOT_040',
        type: 'shot',
        name: 'Escaping into the city',
        code: 'S02-SC03-SH04',
        description: 'A shot of the protagonist escaping into the city streets below.',
        image: 'https://picsum.photos/seed/SHOT_040/400/225',
        duration: 95,
    },
    SHOT_041: {
        id: 'SHOT_041',
        type: 'shot',
        name: 'Running to the helipad',
        code: 'S03-SC02-SH01',
        description: 'A shot of the protagonist running towards the helipad.',
        image: 'https://picsum.photos/seed/SHOT_041/400/225',
        duration: 70,
    },
    SHOT_042: {
        id: 'SHOT_042',
        type: 'shot',
        name: 'Jumping into the helicopter',
        code: 'S03-SC02-SH02',
        description: 'A shot of the protagonist jumping into the helicopter.',
        image: 'https://picsum.photos/seed/SHOT_042/400/225',
        duration: 85,
    },
    SHOT_043: {
        id: 'SHOT_043',
        type: 'shot',
        name: 'Helicopter taking off',
        code: 'S03-SC02-SH03',
        description: 'A shot of the helicopter taking off from the helipad.',
        image: 'https://picsum.photos/seed/SHOT_043/400/225',
        duration: 100,
    },
    SHOT_044: {
        id: 'SHOT_044',
        type: 'shot',
        name: 'Looking down at the city',
        code: 'S03-SC02-SH04',
        description: 'A shot of the protagonist looking down at the city from the helicopter.',
        image: 'https://picsum.photos/seed/SHOT_044/400/225',
        duration: 115,
    },
    SHOT_045: {
        id: 'SHOT_045',
        type: 'shot',
        name: 'Walking through the garden',
        code: 'S03-SC03-SH01',
        description: 'A shot of the protagonist walking through the rooftop garden.',
        image: 'https://picsum.photos/seed/SHOT_045/400/225',
        duration: 90,
    },
    SHOT_046: {
        id: 'SHOT_046',
        type: 'shot',
        name: 'Looking at the city lights',
        code: 'S03-SC03-SH02',
        description: 'A shot of the protagonist looking at the city lights.',
        image: 'https://picsum.photos/seed/SHOT_046/400/225',
        duration: 105,
    },
    SHOT_047: {
        id: 'SHOT_047',
        type: 'shot',
        name: 'A moment of peace',
        code: 'S03-SC03-SH03',
        description: 'A shot of the protagonist having a moment of peace.',
        image: 'https://picsum.photos/seed/SHOT_047/400/225',
        duration: 70,
    },
    SHOT_048: {
        id: 'SHOT_048',
        type: 'shot',
        name: 'Leaving the garden',
        code: 'S03-SC03-SH04',
        description: 'A shot of the protagonist leaving the garden.',
        image: 'https://picsum.photos/seed/SHOT_048/400/225',
        duration: 65,
    },
    SHOT_049: {
        id: 'SHOT_049',
        type: 'shot',
        name: 'Sitting at the table',
        code: 'S04-SC02-SH01',
        description: 'A shot of the protagonist sitting at the interrogation table.',
        image: 'https://picsum.photos/seed/SHOT_049/400/225',
        duration: 80,
    },
    SHOT_050: {
        id: 'SHOT_050',
        type: 'shot',
        name: 'Intense questioning',
        code: 'S04-SC02-SH02',
        description: 'A shot of the protagonist being intensely questioned.',
        image: 'https://picsum.photos/seed/SHOT_050/400/225',
        duration: 95,
    },
    SHOT_051: {
        id: 'SHOT_051',
        type: 'shot',
        name: 'A moment of defiance',
        code: 'S04-SC02-SH03',
        description: 'A shot of the protagonist showing a moment of defiance.',
        image: 'https://picsum.photos/seed/SHOT_051/400/225',
        duration: 110,
    },
    SHOT_052: {
        id: 'SHOT_052',
        type: 'shot',
        name: 'Leaving the room',
        code: 'S04-SC02-SH04',
        description: 'A shot of the protagonist leaving the interrogation room.',
        image: 'https://picsum.photos/seed/SHOT_052/400/225',
        duration: 125,
    },
    SHOT_053: {
        id: 'SHOT_053',
        type: 'shot',
        name: 'Looking at the board',
        code: 'S04-SC03-SH01',
        description: 'A shot of the team looking at the evidence board.',
        image: 'https://picsum.photos/seed/SHOT_053/400/225',
        duration: 70,
    },
    SHOT_054: {
        id: 'SHOT_054',
        type: 'shot',
        name: 'Connecting the dots',
        code: 'S04-SC03-SH02',
        description: 'A shot of a crew member connecting the dots on the board.',
        image: 'https://picsum.photos/seed/SHOT_054/400/225',
        duration: 85,
    },
    SHOT_055: {
        id: 'SHOT_055',
        type: 'shot',
        name: 'A moment of realization',
        code: 'S04-SC03-SH03',
        description: 'A shot of a crew member having a moment of realization.',
        image: 'https://picsum.photos/seed/SHOT_055/400/225',
        duration: 100,
    },
    SHOT_056: {
        id: 'SHOT_056',
        type: 'shot',
        name: 'Getting ready to leave',
        code: 'S04-SC03-SH04',
        description: 'A shot of the team getting ready to leave.',
        image: 'https://picsum.photos/seed/SHOT_056/400/225',
        duration: 60,
    },
    SHOT_057: {
        id: 'SHOT_057',
        type: 'shot',
        name: 'Showing fake passports',
        code: 'S05-SC03-SH01',
        description: 'A shot of the protagonist showing fake passports to the border guard.',
        image: 'https://picsum.photos/seed/SHOT_057/400/225',
        duration: 120,
    },
    SHOT_058: {
        id: 'SHOT_058',
        type: 'shot',
        name: 'Tense moment',
        code: 'S05-SC03-SH02',
        description: 'A tense moment as the guard inspects the passports.',
        image: 'https://picsum.photos/seed/SHOT_058/400/225',
        duration: 150,
    },
    SHOT_059: {
        id: 'SHOT_059',
        type: 'shot',
        name: 'Guard waves them through',
        code: 'S05-SC03-SH03',
        description: 'A shot of the guard waving them through.',
        image: 'https://picsum.photos/seed/SHOT_059/400/225',
        duration: 90,
    },
    SHOT_060: {
        id: 'SHOT_060',
        type: 'shot',
        name: 'Driving away',
        code: 'S05-SC03-SH04',
        description: 'A shot of the car driving away from the border.',
        image: 'https://picsum.photos/seed/SHOT_060/400/225',
        duration: 30,
    },
};